### PR TITLE
Backfilled Engine, Document, and Search APIs

### LINKED ISSUE #28: Search across multiple fields - fails
I have so many fields in my Swiftype engine. I want search across fields. I tried like

```
host_identifier = 'host-XXXX'
api_key = 'search-XXXXX'
client = SwiftypeAppSearch::Client.new(host_identifier: host_identifier, api_key: api_key)
engine_name = 'XXXXX'
queries = ["query" => {"desired_location" => "california"}, "query" => {"job_search_status" => "not_looking"}]  
options = {
    result_fields: {
      id: {raw: {}},
      email: {raw: {}}
    }
  }  
response = client.multi_search(engine_name, queries, options)
```

Getting `NoMethodError - undefined method multi_search for #<SwiftypeAppSearch::Client:0x00007f8794a0af00>`:

https://swiftype.com/documentation/app-search/api/search#multi  >> Based on this we have to use multi_search right?

### PR DESCRIPTION
**Pull request by JasonStoltz**
Fixes #28

Added the following:
- Second parameter to `create_engine` for `language`
- `update_documents` for partial updates
- `list_documents`
- `multi_search`

### CODE REVIEW

File: lib/swiftype-app-search/client/documents.rb [hunk 1]
```diff
@@ -5,13 +5,23 @@ module SwiftypeAppSearch
   class Client
     module Documents
 
+      # Retrieve all Documents from the API for the {App Search API}[https://swiftype.com/documentation/app-search/]
+      #
+      # @param [String] engine_name the unique Engine names
```
Comment (kovyrin) [inline lib/swiftype-app-search/client/documents.rb]:
```suggestion
      # @param [String] engine_name the unique Engine name
```
